# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1fc03202705cd645b9284d2340d3ba98e0800828dce33bf63c6fdc74a3af0bafd0d93d10e36d1b273a8eecd6f964d13d53bec8204611fcc40cacc37e2a87751

test:
  secret_key_base: 42f5c0aa4d48d2d25bf5596d634bd91a8b15d4331c7a4e3319e8adca2c029cf26f14e22e9d9c175e6478cdbb48e5bfef29d67e7e14b5694e1f1f91c5f44d38ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
